on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          NOW=$(date -u +%y%m%d-%H%M%S)
          git switch -c $NOW
          touch toto
          git add toto
          git commit -m $NOW
          gh pr create -B main -H $NOW --title 'Update sec.bib' --body 'Created by Github action'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
